service: testAssignar # NOTE: update this with your service name

plugins:
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  role: DefaultRole
  stage: live
  region: ap-southeast-2
  apiKeys:
    - ${self:provider.stage}-key
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: WEEK
    throttle:
      burstLimit: 200
      rateLimit: 100
  environment:
    USER_DDB_TABLE: ${self:service}-${self:provider.stage}-USER
    TOKEN_DDB_TABLE: ${self:service}-${self:provider.stage}-TOKEN
    IMAGE_BUCKET: testassignar-${self:provider.stage}-image-bucket
    TOKEN_PERIOD_IN_MINUTES: 60 

package:
  exclude:
    - Tests/**
    - .dynamodb/**
    - .vscode/**
    - Utils/**

functions:
  hello:
    handler: testAssignar.hello
    events:
      - http:
          path: hello
          method: get

  adduser:
    handler: testAssignar.adduser
    events:
      - http:
          path: user
          method: put
          private: true

  deleteuser:
    handler: testAssignar.deleteuser
    events:
      - http:
          path: user
          method: delete
          private: true

  getuser:
    handler: testAssignar.getuser
    events:
      - http:
          path: user
          method: get
          private: true

  login:
    handler: testAssignar.login
    events:
      - http:
          path: user/login
          method: post
          private: true

  changepassword:
    handler: testAssignar.changepassword
    events:
      - http:
          path: user/changepassword
          method: post
          private: true

  setupmaster:
    handler: testAssignar.setupmaster
    events:
      - http:
          path: setupmaster
          method: get

resources:
  Resources:
    Imagebucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:provider.environment.IMAGE_BUCKET}

    TokenTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: Token
            AttributeType: S
        KeySchema:
          - AttributeName: Token
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: Expiry
          Enabled: true
        TableName: ${self:provider.environment.TOKEN_DDB_TABLE}

    UserDDBTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: Email
            AttributeType: S
        KeySchema:
          - AttributeName: Email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.USER_DDB_TABLE}

    DefaultRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /testassignar/defaultrole/
        RoleName: testAssignarDefaultRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: testAssignarPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - cloudformation:DescribeChangeSet
                    - cloudformation:DescribeStackResources
                    - cloudformation:DescribeStacks
                    - cloudformation:GetTemplate
                    - cloudformation:ListStackResources
                    - cloudwatch:*
                    - cognito-identity:ListIdentityPools
                    - cognito-sync:GetCognitoEvents
                    - cognito-sync:SetCognitoEvents
                    - dynamodb:*
                    - ec2:DescribeSecurityGroups
                    - ec2:DescribeSubnets
                    - ec2:DescribeVpcs
                    - events:*
                    - iam:GetPolicy
                    - iam:GetPolicyVersion
                    - iam:GetRole
                    - iam:GetRolePolicy
                    - iam:ListAttachedRolePolicies
                    - iam:ListRolePolicies
                    - iam:ListRoles
                    - iam:PassRole
                    - iot:AttachPrincipalPolicy
                    - iot:AttachThingPrincipal
                    - iot:CreateKeysAndCertificate
                    - iot:CreatePolicy
                    - iot:CreateThing
                    - iot:CreateTopicRule
                    - iot:DescribeEndpoint
                    - iot:GetTopicRule
                    - iot:ListPolicies
                    - iot:ListThings
                    - iot:ListTopicRules
                    - iot:ReplaceTopicRule
                    - kinesis:DescribeStream
                    - kinesis:ListStreams
                    - kinesis:PutRecord
                    - kms:ListAliases
                    - lambda:*
                    - logs:*
                    - s3:*
                    - sns:ListSubscriptions
                    - sns:ListSubscriptionsByTopic
                    - sns:ListTopics
                    - sns:Publish
                    - sns:Subscribe
                    - sns:Unsubscribe
                    - sqs:ListQueues
                    - sqs:SendMessage
                    - tag:GetResources
                    - xray:PutTelemetryRecords
                    - xray:PutTraceSegments
                  Resource: '*'