service: testAssignar # NOTE: update this with your service name

plugins:
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  role: DefaultRole
  stage: live
  region: ap-southeast-2
  environment:
      USER_DDB_TABLE: ${self:service}-${self:provider.stage}-USER
      TOKEN_TABLE: ${self:service}-${self:provider.stage}-TOKEN

package:
  exclude:
    - CurlTests/**

functions:
  hello:
    handler: testAssignar.hello
    events:
      - http:
          path: hello
          method: get

  login:
    handler: testAssignar.login
    events:
      - http:
          path: login
          method: post

resources:
  Resources:
    Imagebucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ImageBucket
    TokenTable:
      Type: AWS::DynamodB::Table
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: Token
            AttributeType: S
          - AttributeName: Email
            AttributeType: S
          - AttributeName: UserRole
            AttributeType: S
          - AttributeName: StartTime
            AttributeType: N
          - AttributeName: Duration
            AttributeType: N
        KeySchema:
          - AttributeName: Token
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.TOKEN_TABLE}

    UserDDBTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: Email
            AttributeType: S
          - AttributeName: FirstName
            AttributeType: S
          - AttributeName: LastName 
            AttributeType: S
          - AttributeName: Password
            AttributeType: S
          - AttributeName: ConfirmPassword
            AttributeType: S
          - AttributeName: UserRole
            AttributeType: S
          - AttributeName: ProfilePicture
            AttributeType: S
          - AttributeName: Active
            AttributeType: N
        KeySchema:
          - AttributeName: Email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.USER_DDB_TABLE}

    DefaultRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /testassignar/defaultrole/
        RoleName: testAssignarDefaultRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: testAssignarPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - cloudformation:DescribeChangeSet
                    - cloudformation:DescribeStackResources
                    - cloudformation:DescribeStacks
                    - cloudformation:GetTemplate
                    - cloudformation:ListStackResources
                    - cloudwatch:*
                    - cognito-identity:ListIdentityPools
                    - cognito-sync:GetCognitoEvents
                    - cognito-sync:SetCognitoEvents
                    - dynamodb:*
                    - ec2:DescribeSecurityGroups
                    - ec2:DescribeSubnets
                    - ec2:DescribeVpcs
                    - events:*
                    - iam:GetPolicy
                    - iam:GetPolicyVersion
                    - iam:GetRole
                    - iam:GetRolePolicy
                    - iam:ListAttachedRolePolicies
                    - iam:ListRolePolicies
                    - iam:ListRoles
                    - iam:PassRole
                    - iot:AttachPrincipalPolicy
                    - iot:AttachThingPrincipal
                    - iot:CreateKeysAndCertificate
                    - iot:CreatePolicy
                    - iot:CreateThing
                    - iot:CreateTopicRule
                    - iot:DescribeEndpoint
                    - iot:GetTopicRule
                    - iot:ListPolicies
                    - iot:ListThings
                    - iot:ListTopicRules
                    - iot:ReplaceTopicRule
                    - kinesis:DescribeStream
                    - kinesis:ListStreams
                    - kinesis:PutRecord
                    - kms:ListAliases
                    - lambda:*
                    - logs:*
                    - s3:*
                    - sns:ListSubscriptions
                    - sns:ListSubscriptionsByTopic
                    - sns:ListTopics
                    - sns:Publish
                    - sns:Subscribe
                    - sns:Unsubscribe
                    - sqs:ListQueues
                    - sqs:SendMessage
                    - tag:GetResources
                    - xray:PutTelemetryRecords
                    - xray:PutTraceSegments
                  Resource: '*'